### ISSUE TITLE
Please register it in bower.io

### ISSUE THREAD

**Issue by smsahu** [adamalbrecht/angular-date-picker-polyfill#11]
I am unable to find it using kwyword: angular-date-picker-polyfill from bower.json

**Comment by jacobboland** [comment]
As a work around, you can fork it, tag it and install yours by pointing to your forked repo.

**Comment by adamalbrecht** [comment]
I don't think it's quite stable enough to list on Bower. But you can always just point at the git url

```json
"dependencies": {
  "angular-date-picker-polyfill": "git@github.com:adamalbrecht/angular-date-picker-polyfill.git"
}
```
