### ISSUE TITLE
$compile:multidir. Multiple directives [datepickerPopup, input] in Firefox

### ISSUE THREAD

**Issue by pdorgambide** [adamalbrecht/angular-date-picker-polyfill#17]
[Error: $compile:multidir. Multiple directives [datepickerPopup, input] in Firefox #4106](https://github.com/angular-ui/bootstrap/issues/4106)

**Comment by JoeyLi-1** [comment]
if (!Modernizr.inputtypes.date) {
    angular.module('angular-date-picker-polyfill').directive('input', ["$compile", "aaDateUtil", function($compile, aaDateUtil) { 

@adamalbrecht Please change this implementation. This cost me 2 days to locate the root cause. Who will define a directive which have same name of html tags? That is definitely the worst idea.

**Comment by adamalbrecht** [comment]
@JoeyLi-1 Using an html tag as the name of the directive is the entire purpose of the project - that's why it's called "polyfill". Feel free to fork and change it.

**Comment by JoeyLi-1** [comment]
Okay. Thank you! @adamalbrecht
